server:
  port: 8084
spring:
  flyway:
    enabled: false
  application:
    name: fire-duty-rectification
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.32.156}:${DB_PORT:15432}/${DB_NAME:fire_duty}
    username: ${DB_USER:fire_duty}
    password: ${DB_PASS:gpte1956}
    driver-class-name: org.postgresql.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
  type-aliases-package: com.fireduty.rectification.entity
