server:
  port: 8081
spring:
  flyway:
    enabled: false
  application:
    name: fire-duty-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.32.156}:${DB_PORT:15432}/${DB_NAME:fire_duty}
    username: ${DB_USER:fire_duty}
    password: ${DB_PASS:gpte1956}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
jwt:
  secret: fireduty-jwt-secret-change-in-production
  expiration: 86400000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.fireduty.auth.entity
